apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:nlgKBoEVgeOBtpqKXCrqDSihUiXk5ZFoZh52cAFOrtcydQaEN4lGfow5jE8nG0IOEuE8lLg=,iv:ly1rIIT8xFTqEzOIi0KgF8gNkhimruTCh3rjNtd90YU=,tag:Ho1/ewxuRkCQPOWLpwzqGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ylchw4va5380jsvvyl3gugmtpptghftkeza4nrxnm8j3hym9jd3saj8yg3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT2IyNmEvVmovMW5NMTVM
            NkRhL3dmRW1nSGNreEk1K1BkZDZmYUFna0JZCmJFK0dJQ0dqdHBJYVZtUnp3Z1NX
            WnRGMzZzbVFYZDQ4Z0pTZ0NIanUvaDgKLS0tIGxBRThKeU5sclFUbmp0SXlUZ0pB
            a2JYdHBQT2JmYWxQSUpGWlBHbS85S2cK8zLVYyALw/wHmzwgCTnJnBbIspCNe+01
            uXVsV/TwugaF7gpvX1sFNJwjKGh4R8oZOM2cFJQrdOKkw9Fsq+26rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T03:14:31Z"
    mac: ENC[AES256_GCM,data:UF7u4CJ6Pax8GK8ulR2ODYkI8JqeZ74OyfeDCeG3E4m/B70ntoXr01CwDxwl3LEo9kbnaU0CnmPAsvQtnTT/xOqsglBpXpGFCojrqb8e2t8hYt8OcrMyqHLVTiA7Dl+w6BPyg7H5/krVr4bEc7EVCV5A9olZzpvz006727M24Ho=,iv:cUQ/QeMYz/fViwaM37E5lgB3BQKLoRdka5SzvK4FDRc=,tag:td+qGMstp1CyQP/RW+oypA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
