apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ty753jc=,iv:myaRFsvQr2ajnvC25k0vy7jFsrA/hKyNlV+pHezDb04=,tag:gjkUw1ciHamh0N8rg878AQ==,type:str]
    password: ENC[AES256_GCM,data:nYVdweAljyss5PA=,iv:w16Cn+37OLg53XrW9c3f/TN47B3+XrTuLjCvnksGxWc=,tag:+NLu/L7HSkbMUrZuVZLWcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ylchw4va5380jsvvyl3gugmtpptghftkeza4nrxnm8j3hym9jd3saj8yg3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K3cxQXl5WjlIYWdVenZk
            Ty9vSWJDT0M3a1FXNmhSdEJ3aGJYNVVHNUJFCjhrK2pXM01aUUtlR2k2WmtuYUov
            M3c2NGp1QThZNXNYc3gwRWRQMmdEUHMKLS0tIElybyt3Mkxxb0p1Q3p1LytIRlpF
            MjNvbWpqeUtmYWgyTndCMTJzcnJOblEKSfF68gNRrgmiMCVmnz84toUtcT1pcsp6
            1zZyWJGdalQwcC2UWdpPInM9qSdOcrhfb0RpZwPCFcn/c9nGeAJRvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T15:11:41Z"
    mac: ENC[AES256_GCM,data:2l2N82ykxCzPkJrU3kKpq8QaxXm7kxFIUHn14+Mh735S7GjV61Bl2p+yB85Ytd30iEN7waIlyuzZPDFJ9zrSfDC3tol2mwZH/+vJmo7UBiN3VgqrXyCuiSUf9G+Aja+jAluPswfukOsNnqdvjNTAvFttga/5QtM0A/AxZk/QKFs=,iv:keOWTrxkQiV5sbHJ0iCtiOlvrO1t5tTZjoAMmoaWFkI=,tag:BxNEktWHm4bTRV8me7z3rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
