apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ty753jc=,iv:myaRFsvQr2ajnvC25k0vy7jFsrA/hKyNlV+pHezDb04=,tag:gjkUw1ciHamh0N8rg878AQ==,type:str]
    password: ENC[AES256_GCM,data:nYVdweAljyss5PA=,iv:w16Cn+37OLg53XrW9c3f/TN47B3+XrTuLjCvnksGxWc=,tag:+NLu/L7HSkbMUrZuVZLWcA==,type:str]
    cloud_flare: ENC[AES256_GCM,data:uxB9sFFSYUexfl9QgepptQMTQk87lZH0PJmm8gkwrL4nzNrpSQTTbbdDWxIrSVKE3Os9X3A=,iv:AQtvspz7a7ydre3cgaN+SCagDQCS8iu4zH5r+xN6TQs=,tag:IK1UG6cL2XFE8FMFcSPkvQ==,type:str]
    github_user: ENC[AES256_GCM,data:Fec+q0HfbvaUsb92,iv:UCLYxTcx4ICpbUolMVSjY02s2Wj2OeQtqmtsKT6Q4z0=,tag:WtbgSLOnSqJVIqeRnwIQDw==,type:str]
    github_token: ENC[AES256_GCM,data:yUfpPJuR/lGXeDTciu7VMtbNnfaIHeiKz/3+jeo8LEsD+5OWy8Xcmg==,iv:o8d6uYXqLAOMKZyzoecw8YFhMYei2LaEIaovn9QJR0M=,tag:YLrw4dg887pHaiZe6c6Dqw==,type:str]
    github_repo: ENC[AES256_GCM,data:xQrDkNoqag==,iv:9K1X81nin35YltbnPW0rhm9JiuG49gu3zpor+LcLjDQ=,tag:3Bz8UYYV8CYi1AywBZg3cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ylchw4va5380jsvvyl3gugmtpptghftkeza4nrxnm8j3hym9jd3saj8yg3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K3cxQXl5WjlIYWdVenZk
            Ty9vSWJDT0M3a1FXNmhSdEJ3aGJYNVVHNUJFCjhrK2pXM01aUUtlR2k2WmtuYUov
            M3c2NGp1QThZNXNYc3gwRWRQMmdEUHMKLS0tIElybyt3Mkxxb0p1Q3p1LytIRlpF
            MjNvbWpqeUtmYWgyTndCMTJzcnJOblEKSfF68gNRrgmiMCVmnz84toUtcT1pcsp6
            1zZyWJGdalQwcC2UWdpPInM9qSdOcrhfb0RpZwPCFcn/c9nGeAJRvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T09:56:20Z"
    mac: ENC[AES256_GCM,data:fA3zc7oTe4SfF8mKDCjg7ZBcMz4uJcVz4zLAZGWVWeAMxfx3Bxbp8N4kY0dB5kCt9frHZyzOQecyIdEr4y+Ah55R1sN6uQMwcecfhclRB6bls1ky2+4PTN5EfzH8CnL1cll5sFpkolC6oip5ZWreP05dq+bipmTKehAn2erabg8=,iv:p6i6rcfScZvOkwuMTl99ubn7fxxvGt+30Uxppf9td1k=,tag:y8tqeerQJ9oHbE89fUT8Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
